package com.example.projet07.parsers.performance;
/* Generated By:JavaCC: Do not edit this line. PerformanceTacticParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PerformanceTacticParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int LITERAL = 5;
    /** RegularExpression Id. */
    int CALLER = 6;
    /** RegularExpression Id. */
    int CALLEE = 7;
    /** RegularExpression Id. */
    int METHOD = 8;
    /** RegularExpression Id. */
    int COMMA = 9;
    /** RegularExpression Id. */
    int SEMICOLON = 10;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = {
            "<EOF>",
            "\"\\n\"",
            "\" \"",
            "\"\\t\"",
            "\"\\r\"",
            "<LITERAL>",
            "\"CALLER:\"",
            "\"CALLEE:\"",
            "\"METHOD:\"",
            "\",\"",
            "\";\"",
    };

}